name: Deploy

on: [push]

jobs:
  deploy-get-obituaries:
    runs-on: ubuntu-latest

    env:
      BUCKET: the-last-show-30145429

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: create deployment package
        run: |
          cd functions/get-obituaries
          mkdir ./package && pip install -r requirements.txt -t ./package
          cd package && zip -r9 ../get-obituaries-artifact.zip .
          cd ../ && zip -g get-obituaries-artifact.zip main.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      
      - name: upload to s3
        run: aws s3 cp get-obituaries-artifact.zip s3://${{ env.BUCKET }}/get-obituaries-artifact.zip

  deploy-create-obituary:
    runs-on: ubuntu-latest

    env:
      BUCKET: the-last-show-30145429

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: create deployment package
        run: |
          cd functions/create-obituary
          mkdir ./package && pip install -r requirements.txt -t ./package
          cd package && zip -r9 ../create-obituary-artifact.zip .
          cd ../ && zip -g create-obituary-artifact.zip main.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      
      - name: upload to s3
        run: aws s3 cp create-obituary-artifact.zip s3://${{ env.BUCKET }}/create-obituary-artifact.zip
